M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date Sun 15 May 2022 01:38:22 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-15T13:38:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X130.4Y-74.445
X130.4Y-130.055
T0
M30
